bind_addr = ":8080"
log_level = "debug"
database_url = "host=localhost user=markit password=132 dbname=restapi_dev sslmode=disable"
session_key = "hugivnnijwbevfjnpfv82937ntng2ncntgrfgn29t07ty20ntn20nt9gm2985cnty7"

database_students_table_url = "host=localhost user=markit password=132 dbname=students sslmode=disable"